version: "2"

run:
  timeout: 2m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true

exclusions:
  generated: lax
  paths:
    - third_party$
    - builtin$
    - examples$

issues:
  exclude-use-default: false
