FROM golang:1.24-alpine AS dev

# Set working directory
WORKDIR /app

# Install dependencies
RUN apk add --no-cache git curl

# Install Air for hot reload
RUN go install github.com/air-verse/air@latest

# Copy Go modules separately to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy only source code (you will override it with volume in dev)
COPY . .

# Run Air (use .air.toml if exists)
CMD ["air", "-c", ".air.toml"]
