services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.local
    environment:
      DATABASE_URL: postgres://gohotels:secret@db:5432/gohotels?sslmode=disable
      APP_ENV: local
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
