services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gohotels
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gohotels
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gohotels"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://gohotels:secret@db:5432/gohotels?sslmode=disable
      APP_ENV: local
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
