services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gohotels
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gohotels
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gohotels"]
      interval: 3s
      timeout: 3s
      retries: 5
