services:
  db:
    ports:
      - "5432:5432"
    volumes: [] # No persistence in CI

  api:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes: [] # No bind mounts in CI
    environment:
      DATABASE_URL: postgres://gohotels:secret@db:5432/gohotels?sslmode=disable
      APP_ENV: test
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
