server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/traces
metrics_generator:
  # optional but good in single-binary
  ring:
    kvstore:
      store: memberlist
  processor:
    service_graphs: {}
    span_metrics:
    # optional tuning
    # histogram_buckets: [1ms, 2ms, 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s]
  storage:
    path: /var/tempo/metrics # <-- required local path for MG WAL/buffer
    remote_write:
      - url: http://prometheus:9090/api/v1/write
