// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Hotel struct {
	ID            pgtype.UUID
	Name          string
	City          string
	Stars         int32
	PricePerNight pgtype.Numeric
	Amenities     []string
}
