// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateHotel(ctx context.Context, arg CreateHotelParams) (Hotel, error)
	ListHotels(ctx context.Context, city string) ([]Hotel, error)
}

var _ Querier = (*Queries)(nil)
