// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Hotel defines model for Hotel.
type Hotel struct {
	Amenities     *[]string           `json:"amenities,omitempty"`
	City          *string             `json:"city,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	Name          *string             `json:"name,omitempty"`
	PricePerNight *float32            `json:"price_per_night,omitempty"`
	Stars         *int                `json:"stars,omitempty"`
}

// HotelInput defines model for HotelInput.
type HotelInput struct {
	Amenities     []string `json:"amenities"`
	City          string   `json:"city"`
	Name          string   `json:"name"`
	PricePerNight float32  `json:"price_per_night"`
	Stars         int      `json:"stars"`
}

// CheckInParam defines model for CheckInParam.
type CheckInParam = openapi_types.Date

// CheckOutParam defines model for CheckOutParam.
type CheckOutParam = openapi_types.Date

// CityParam defines model for CityParam.
type CityParam = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error *string `json:"error,omitempty"`
}

// ListHotelsParams defines parameters for ListHotels.
type ListHotelsParams struct {
	City     CityParam      `form:"city" json:"city"`
	Checkin  *CheckInParam  `form:"checkin,omitempty" json:"checkin,omitempty"`
	Checkout *CheckOutParam `form:"checkout,omitempty" json:"checkout,omitempty"`
}

// CreateHotelJSONRequestBody defines body for CreateHotel for application/json ContentType.
type CreateHotelJSONRequestBody = HotelInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List hotels
	// (GET /hotels)
	ListHotels(w http.ResponseWriter, r *http.Request, params ListHotelsParams)
	// Create a new hotel
	// (POST /hotels)
	CreateHotel(w http.ResponseWriter, r *http.Request)
	// Readiness check
	// (GET /ready)
	GetReady(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List hotels
// (GET /hotels)
func (_ Unimplemented) ListHotels(w http.ResponseWriter, r *http.Request, params ListHotelsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new hotel
// (POST /hotels)
func (_ Unimplemented) CreateHotel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness check
// (GET /ready)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHotels operation middleware
func (siw *ServerInterfaceWrapper) ListHotels(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHotelsParams

	// ------------- Required query parameter "city" -------------

	if paramValue := r.URL.Query().Get("city"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "city"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "city", r.URL.Query(), &params.City)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "city", Err: err})
		return
	}

	// ------------- Optional query parameter "checkin" -------------

	err = runtime.BindQueryParameter("form", true, false, "checkin", r.URL.Query(), &params.Checkin)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "checkin", Err: err})
		return
	}

	// ------------- Optional query parameter "checkout" -------------

	err = runtime.BindQueryParameter("form", true, false, "checkout", r.URL.Query(), &params.Checkout)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "checkout", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHotels(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHotel operation middleware
func (siw *ServerInterfaceWrapper) CreateHotel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHotel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hotels", wrapper.ListHotels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/hotels", wrapper.CreateHotel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.GetReady)
	})

	return r
}

type BadRequestJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status *string `json:"status,omitempty"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListHotelsRequestObject struct {
	Params ListHotelsParams
}

type ListHotelsResponseObject interface {
	VisitListHotelsResponse(w http.ResponseWriter) error
}

type ListHotels200JSONResponse []Hotel

func (response ListHotels200JSONResponse) VisitListHotelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListHotels400JSONResponse struct{ BadRequestJSONResponse }

func (response ListHotels400JSONResponse) VisitListHotelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateHotelRequestObject struct {
	Body *CreateHotelJSONRequestBody
}

type CreateHotelResponseObject interface {
	VisitCreateHotelResponse(w http.ResponseWriter) error
}

type CreateHotel201JSONResponse Hotel

func (response CreateHotel201JSONResponse) VisitCreateHotelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateHotel400Response struct {
}

func (response CreateHotel400Response) VisitCreateHotelResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateHotel500Response struct {
}

func (response CreateHotel500Response) VisitCreateHotelResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(w http.ResponseWriter) error
}

type GetReady200JSONResponse struct {
	Db     *string `json:"db,omitempty"`
	Status *string `json:"status,omitempty"`
}

func (response GetReady200JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReady503JSONResponse struct {
	Db     *string `json:"db,omitempty"`
	Status *string `json:"status,omitempty"`
}

func (response GetReady503JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List hotels
	// (GET /hotels)
	ListHotels(ctx context.Context, request ListHotelsRequestObject) (ListHotelsResponseObject, error)
	// Create a new hotel
	// (POST /hotels)
	CreateHotel(ctx context.Context, request CreateHotelRequestObject) (CreateHotelResponseObject, error)
	// Readiness check
	// (GET /ready)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListHotels operation middleware
func (sh *strictHandler) ListHotels(w http.ResponseWriter, r *http.Request, params ListHotelsParams) {
	var request ListHotelsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHotels(ctx, request.(ListHotelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHotels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHotelsResponseObject); ok {
		if err := validResponse.VisitListHotelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateHotel operation middleware
func (sh *strictHandler) CreateHotel(w http.ResponseWriter, r *http.Request) {
	var request CreateHotelRequestObject

	var body CreateHotelJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateHotel(ctx, request.(CreateHotelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateHotel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateHotelResponseObject); ok {
		if err := validResponse.VisitCreateHotelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(w http.ResponseWriter, r *http.Request) {
	var request GetReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx, request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVTW/cNhD9KwTbQwsIq03TAoFucQ71ogESuL0lRjBLza4YSyQ9HK27MPTfiyH3S16h",
	"m8Bub6I4fDPzHvnmURvfBe/QcdTVow5A0CEjpdW7Bs3dwn2Un7K2Tlf6vkfa6kI76FBX2kiMdbrQ0TTY",
	"gcStPHXAutI1MOpC8zZIaGSybq2HocjIH3q+DO17/l5sy9t/x7UsK8L73hLWumLq8TTHU8xBgmPwLmLi",
	"5QrqG7zvMbKsjHeMLn1CCK01wNa78mv0Tv4dYQP5gMQ2gyCRp6lsh5788isazvlrjIZsEGRdSQGKdhXI",
	"bs6RYK89Y3ueDTp0dr+wjF2cSH3IDESwlXWiairQ1iMx+t7W52LsGZ84H8ga/BKQvji7bngEtmo98BHN",
	"9d0SSQ5FBjqt2zrGtWydc1ZkIhYu9Pzfs/H/tXm8tJ9y1mJ/nfOp85TFSbe3k3fLupWXdOM79ldjo3r7",
	"caGgbf1DVH1Eioq9ighkGrXypBrhOBbKEAKjWnp/Z906FgpcrdbokOQ3YfDEcfbZLVjZqAIQK79SoJZg",
	"7tDVSgAto+GeUMXGPxiIqAJ5KXL2WdyFLbdSeJJVXeVMUp8u9AYp5qLns1ezuXDoAzoIVlf69Ww+ey28",
	"ADeJ1bJBaLmRzzXyeeM3yD25qD78oexKcYOJhUDeYIxSP/XOWbee6ZSG0nNf1LrSvyNfZ+wnhvHLfP4M",
	"p4gM3GfP+Bu6kGjwd5Ped9E5/kTaWIPSRms3mN2j7zqgra70e7tBJ10m602bZdb4hK1xz+9t5OscUozG",
	"x6dH/SPhSlf6h/I4ZMpjSHk06qG4HHw6i741/jBhhttnKnIwiam0O/sts/eeGce5Cm9Va2N6Azt2h0L/",
	"miuawj9UXp5MnqfKRd6DFZphLQrshsGtGJGPE+K9S+82R2VvwchXvt5+FzcXKckuPIz9S4bucKbKq5fN",
	"PEV+dpBsWfUJ8+OohdtAa2tlc+2F/m0qSp4TksqzfKxI5laBcviQlcnviRAyv5Pmk65tFOOBtlV7tlSN",
	"AV2NzliM6iecrWeFqoFhCRF/VkCosqltJ03pJqV8UU+ql5f9qJh0LtoV8zzzyihJltcv2IbxzqGRo2oF",
	"tsX6W7vq3U6AZ3fmPO+7G90nEdGOzFm20/3LbttTqyvdMIeqLFtvoG185OrN/M1cD7fDPwEAAP//eDEN",
	"busLAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
